### ISSUE TITLE
关于REP规则的小疑问

### ISSUE THREAD

**Issue by NoHeartPen** [MrCorn0-0/hunspell_ja_JP#2]
我查阅了这里的[man 4 Hunspell](https://linux.extremeoverclocking.com/man/4/hunspell)发现REP规则并没有3个参数，只需要写成`REP かけ  掛け`就可以了

![](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220924150718.png)
我在自己电脑上进行测试发现结果完全一致：
![](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220924150740.png)

我很奇怪您为什么会这样写，因为上面提到的手册并没有提到REP有这样的规则（我英语不是很好，并没有完全理解手册中的所有内容，但尽力把所有文字都过了一遍），

（我对日语也能像英语一样，完全通过剪贴板查词很有兴趣，做过一个[《日本語非辞書形辞典》](https://github.com/NoHeartPen/NonJishoKei)，所以对类似的技术也有浓厚的兴趣，抱着讨论问题的想法特地开了个issue向您请教。）

**Comment by MrCorn0-0** [comment]
@NoHeartPen 
您好，非常感谢交流。
因为是两年前的业余创作且之后也没有更深入的探究，时间久远加上当时参考的文章也没有保存下来，说实话我也不记得当时为什么当时这么写了。
但正如您所说的，**关于REP的语法并没有看到有三个参数的使用例**。我刚刚也稍作测试，发现**删掉第三个参数确实不影响功能**。
根据我的“猜测“，从后面写的 ` REP や 遣 や[らりるれろっ]` 来看，当时的我应该是直接根据 PFX/SFX 的语法推测REP也具有第三个参数（尽管说明文档上没有记载且其他地方没有使用例）用于指定适用条件。

拜读了您的项目，我深感敬佩。您对于通过剪贴板查词的想法我非常赞同，这也是我制作这份hunspell的日语morphology的原因。

因为在手机上使用的场景更多，我当时也制作了一份mdx的辅助性词典 [日本語用言活用辞書](https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=40881)，专门用于查询词语的原形和各种变形，并提供跳转的超链接方便跳转到其他辞书的词条页，但是使用感还是略clumsy。加上手机端可能大家更愿意使用MOJi这种更易上手的辞书软件，而且MOJi也提供词形预测功能，我以为电脑端的hunspell就会更加无人问津了。感谢您的讨论和交流。

**Comment by NoHeartPen** [comment]
感谢您答疑解惑~另外，才意识到您就是我现在才开始翻的《日本語用言活用辞書》的制作者，您特意支持的文語型对我的帮助真的很大（本来对古语没有什么兴趣，但脑子一热想让《日本語非辞書形辞典》也支持古语就选修了古文，最近正处于痛苦的过渡区，您的《日本語用言活用辞書》真的是救我于水火之中:)

**Comment by MrCorn0-0** [comment]
感谢您的支持！能对其他使用者带来些许的便利和快乐的话，我觉得自己制作这些的功夫就都有价值了！
当时加入古语纯粹是因为被三省堂的词典荼毒很深。因为里面标记了词语的文语词性，抱着“既然有这样的现成的资源那何必不顺便支持一下这部分呢”的心态便逼自己学了半吊子的文语用言变形（在您这样的日语专业人士面前说这些还真班门弄斧）。连我自己都没有在用的这部分功能，没想到还是能派上用场！！こちらこそ感謝します。
