### ISSUE TITLE
关于MAP规则的小疑问

### ISSUE THREAD

**Issue by NoHeartPen** [MrCorn0-0/hunspell_ja_JP#3]
这里[man 4 Hunspell](https://linux.extremeoverclocking.com/man/4/hunspell)提到了`Use parenthesized groups for character sequences (eg. for composed Unicode characters)`，

```md
MAP 3 
MAP ß(ss)  (character sequence) 
MAP fi(fi)  ("fi" compatibility characters for Unicode fi ligature) 
MAP (ọ́)o   (composed Unicode character: ó with bottom dot)
```

但您的写法与示例有很大的差别（您把2个参数都用括号括起来了）：
![](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220924150615.png)

我将括号去掉之后发现拼写建议的结果是完全一样的，有点好奇，所以专程向您请教下这么写原因:)
![](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220924150610.png)

**Comment by MrCorn0-0** [comment]
您好，感谢指正。
如您所说，使用例没有把两者都用括号括起来，为了简便性和易读性确实应该删掉括号。但是根据hunspell文档描述，括号只是用于group一个unicode的复合字符，前后两者都加括号应该不影响功能。其给出的使用例中没有前后两者都是复合字符的情况，所以没有出现两个括号组。
我当时的写法应该是一种更保守的approach：不仅是这些拗音，后面还有一些历史假名遣，为防止识别不到这些字符，便都统一用括号括起来了。

**Comment by NoHeartPen** [comment]
原来是这样呀，我在做《日本語非辞書形辞典》时也发现拗音、踊り字需要单独考虑，不过历史假名遣还没有做专门的优化，感谢您为之后的优化提供宝贵的思路:)
